baseurl = "https://groktop.us/"
title = "groktopus"
subtitle = "To be is to know."
author = "Magnus Hedemark"
copyright = "Copyright © 2018, Magnus Hedemark; all rights reserved."
canonifyurls = true
#defaultContentLanguage = "en"
#disqusShortname = "groktopus-1"
#enableEmoji = true
#enableRobotsTXT = true
googleAnalytics = "UA-129056468-1"
languageCode = "en-us"
#pygmentsCodeFences = true
#pygmentsStyle = "native"
#pygmentsUseClasses =  true
theme = "newsprint"
[permalinks]
  posts = "/:year/:month/:day/:slug/"
