baseurl = "https://groktop.us/"
title = "groktopus"
#author = "Magnus Hedemark"
copyright = "Copyright © 2018, Magnus Hedemark; all rights reserved."
canonifyurls = false
paginate = 3
defaultContentLanguage = "en"
disqusShortname = "groktopus-1"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-129056468-1"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "minimal"
[author]
  gravatarEmail = "magnus.hedemark@protonmail.ch"
  homepageText = "groktopus"
  name = "Magnus Hedemark"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params]
  adsenseClient = ''
  adsenseSlot = ''
  description = "A blog about everything."
  subtitle = "A blog about everything."
  licence = "Copyright 2018, Magnus Hedemark"
  displayPostLanguage = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[params.logo]
  logoText = "groktopus"
[params.writers."Magnus Hedemark"]
  link = "https://groktop.us"
  email = "magnus@groktop.us"
  bio = [ "Magnus is the head groktopus." ]
  twitter = "https://twitter.com/Magnus919"
  linkedin = "https://linkedin.com/in/hedemark"
  instagram = "https://instagram.com/Magnus919"
  github = "https://github.com/magnus919"
[params.social]
#  facebook      = "full Social profile url in facebook"
#  googleplus    = "full profile url in googleplus"
  email         = "magnus@groktop.us"
#  twitter       = "full profile url in twitter"
#  linkedin      = "full profile url in linkedin"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
#  github        = "full profile url in github"
#  pinterest     = "full profile url in pinterest"
  rss = true

#[params.writers."Göran Svensson"]
#  link = "https://appernetic.io/"
#  email = "goran@molnsys.com"
#  bio = ["Göran is an avid blogger and the founder of <a href='https://appernetic.io/'>Appernetic.io</a>. This is the author bio shown after posts."]
#  facebook      = "full Göran profile url in facebook"
#  googleplus    = "full profile url in googleplus"
#  twitter       = "full profile url in twitter"
#  linkedin      = "full profile url in linkedin"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
#  github        = "full profile url in github"
#  pinterest = "full profile url in pinterest"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
